name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  notify-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    
    steps:
    - name: Notify Discord - New Push
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: |
          🚀 **New push to `{{ EVENT_PAYLOAD.repository.name }}`**
          📝 Commit: `{{ EVENT_PAYLOAD.head_commit.message }}`
          👤 Author: {{ EVENT_PAYLOAD.head_commit.author.name }}
          🔗 [View commit]({{ EVENT_PAYLOAD.head_commit.url }})

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Notify Discord - Tests Starting
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: |
          🧪 **Tests starting** for `{{ GITHUB_REPOSITORY }}`
          📋 Run: [#{{ GITHUB_RUN_NUMBER }}]({{ GITHUB_SERVER_URL }}/{{ GITHUB_REPOSITORY }}/actions/runs/{{ GITHUB_RUN_ID }})
    
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linter
      run: npm run lint
    
    - name: Run unit and integration tests
      run: npm run test:coverage
    
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
    
    - name: Run E2E tests
      run: npm run test:e2e
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          test-results/
          coverage/
          playwright-report/
        retention-days: 7
    
    - name: Notify Discord - Tests Completed
      uses: Ilshidur/action-discord@master
      if: always()
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: |
          ${{ job.status == 'success' && '✅ **Tests passed**' || '❌ **Tests failed**' }} for `{{ GITHUB_REPOSITORY }}`
          📋 Run: [#{{ GITHUB_RUN_NUMBER }}]({{ GITHUB_SERVER_URL }}/{{ GITHUB_REPOSITORY }}/actions/runs/{{ GITHUB_RUN_ID }})

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Notify Discord - Deploy Starting
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: |
          🚀 **Deployment starting** for `{{ GITHUB_REPOSITORY }}`
          📋 Run: [#{{ GITHUB_RUN_NUMBER }}]({{ GITHUB_SERVER_URL }}/{{ GITHUB_REPOSITORY }}/actions/runs/{{ GITHUB_RUN_ID }})
    
    - uses: actions/checkout@v4
    
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v41.1.4
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        vercel-args: '--prod'
        working-directory: ./
    
    - name: Notify Discord - Deploy Completed
      uses: Ilshidur/action-discord@master
      if: always()
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: |
          ${{ job.status == 'success' && '🎉 **Deployment successful**' || '💥 **Deployment failed**' }} for `{{ GITHUB_REPOSITORY }}`
          🌐 Live at: https://www.drawscale.app
          📋 Run: [#{{ GITHUB_RUN_NUMBER }}]({{ GITHUB_SERVER_URL }}/{{ GITHUB_REPOSITORY }}/actions/runs/{{ GITHUB_RUN_ID }})